### PR TITLE
Implement flavor and capabilities support

### PR DESCRIPTION
**Pull request by datacharmer**
* Implement Issue #49 Add support for `--client-from=X`
* Implement Issue #50 Change evaluation of version to include a flavor
* Fix Issue #51 unpack command fails when tarball name doesn't include a version
* Implement Issue #52 unpack command should create a FLAVOR file for the extracted tarball
* Add command `dbdeployer admin capabilities [flavor [version]]`

This is provisional work to allow starting on Issue #54 

cc: 
@percona-csalguero 
@morgo 
@askdba

### CODE REVIEW

**Comment by morgo** [comment]
Awesome!!! I will test it out.

**Comment by morgo** [comment]
I think I found a bug (or at least undefined behavior).  Reproducing the steps -

This looks good - the version is unknown:
```
$ dbdeployer unpack tidb-latest-linux-amd64.tar.gz 
unpack: No version was detected from tarball name. 
Flag --unpack-version becomes mandatory
```

So then I tried this:
```
dbdeployer unpack --unpack-version=3.0.0 --flavor=tidb tidb-latest-linux-amd64.tar.gz 
Unpacking tarball tidb-latest-linux-amd64.tar.gz to $HOME/opt/mysql/3.0.0
.17
Renaming directory /home/morgo/opt/mysql/tidb-latest-linux-amd64 to /home/morgo/opt/mysql/3.0.0
morgo@ryzen:/tmp$ dbdeployer versions
Basedir: /home/morgo/opt/mysql
4.1.22  5.0.96  5.1.72  5.5.61  5.6.42  5.7.24  8.0.13  
```
As you can see, the command worked, but the package is not in the list of deployable versions.  If I `cd` to the location, it looks like it imported correctly:

```
morgo@ryzen:~/opt/mysql$ cd 3.0.0/
morgo@ryzen:~/opt/mysql/3.0.0$ ls
bin  FLAVOR
morgo@ryzen:~/opt/mysql/3.0.0$ more FLAVOR 
tidb
```

I also tried to do this with the alternative command of:
```
 dbdeployer unpack --unpack-version tidb3.0.0 tidb-latest-linux-amd64.tar.gz 
Unpacking tarball tidb-latest-linux-amd64.tar.gz to $HOME/opt/mysql/tidb3.0.0
.17
Renaming directory /home/morgo/opt/mysql/tidb-latest-linux-amd64 to /home/morgo/opt/mysql/tidb3.0.0
```

It looks like it unpacked okay, and also detected flavor correctly, but will not show up in versions:
```
morgo@ryzen:/tmp$ cd ~/opt/mysql/tidb3.0.0/
morgo@ryzen:~/opt/mysql/tidb3.0.0$ ls
bin  FLAVOR
morgo@ryzen:~/opt/mysql/tidb3.0.0$ more FLAVOR 
tidb               
morgo@ryzen:~/opt/mysql/tidb3.0.0$ dbdeployer versions
Basedir: /home/morgo/opt/mysql
4.1.22  5.0.96  5.1.72  5.5.61  5.6.42  5.7.24  8.0.13  
```

**Comment by morgo** [comment]
This might also help diagnose:
```
morgo@ryzen:~/opt/mysql/tidb3.0.0$ dbdeployer deploy single tidb3.0.0
--------------------------------------------------------------------------------
Looking for *linux* binaries
--------------------------------------------------------------------------------
incorrect tarball detected
```
(I haven't tried to install custom templates yet - I assume that this is all pre-flight checking.)

**Comment by datacharmer** [comment]
> morgo@ryzen:~/opt/mysql/tidb3.0.0$ dbdeployer deploy single tidb3.0.0
> --------------------------------------------------------------------------------
> Looking for *linux* binaries
> --------------------------------------------------------------------------------
> incorrect tarball detected
> ```

I haven't addressed this point yet. Thanks for reminding me. We need an issue about this. This chack should be integrated into the flavors detection.

**Comment by datacharmer** [comment]
> the command worked, but the package is not in the list of deployable versions
Please file an issue for this as well. The repo is listed only if there is a "./bin/mysqld" file.

**Comment by morgo** [comment]
Sounds good to me.  I spotted where the check was, and simply adding TiDB allowed it to procceed to running templates:
```
morgo@ryzen:~/go/src/github.com/datacharmer/dbdeployer$ git diff
diff --git a/common/checks.go b/common/checks.go
index 8ff5760..11844bc 100644
--- a/common/checks.go
+++ b/common/checks.go
@@ -191,6 +191,7 @@ func CheckTarballOperatingSystem(basedir string) error {
                "libmysqlclient.dylib":         {"lib", "darwin", "mysql", true},
                "table.h":                      {"sql", "source", "any", false},
                "mysqlprovision.zip":           {"share/mysqlsh", "shell", "any", false},
+               "tidb-server":                  {"bin", "linux", "tib", true},
        }
```

Outcome:
```
morgo@ryzen:~/go/src/github.com/datacharmer/dbdeployer$ dbdeployer deploy single tidb3.0.0
SCRIPT
error creating sandbox: 'script '/home/morgo/opt/mysql/tidb3.0.0/scripts/mysql_install_db' not found'
```

**Comment by morgo** [comment]
After I manually created `./scripts/mysql_install_db` the sandbox installed.  Would you like a bug report about moving this into flavors as well?

**Comment by datacharmer** [comment]
> Would you like a bug report about moving this into flavors as well?

No need. This should already work with flavors, but apparently I haven't run enough tests. Will debug

**Comment by datacharmer** [comment]
Latest commits should fix all the issues. Then I will start expanding the tests.

**Comment by datacharmer** [comment]
Added tiDB templates

**Comment by datacharmer** [comment]
Blast, I found a bug in my implementation of TiDB templates. 
As it is now, the command `dbdeployer defaults templates show templateName` will show the template from `single` and now from `tidb`.  There is a non-enforced assumption that the template names must be unique, and I broke it when I put together the TiDB collection.
I need to use different names and to add a check about the template names being unique.

**Comment by morgo** [comment]
I think the ux of remote download is broken by `--flavor`:
```
➜  ~ ~/bin/dbdeployer-1.18.1.osx remote download 5.7.25
File /Users/morgo/5.7.25.tar.xz downloaded
➜  ~ ~/bin/dbdeployer-1.18.1.osx unpack 5.7.25.tar.xz  
No flavor detected in 5.7.25.tar.xz. Please use --flavor
➜  ~ ~/bin/dbdeployer-1.18.1.osx unpack 5.7.25.tar.xz --flavor mysql
```
It would be nice if the downloaded file could describe itself as mysql flavor so I can skip this argument?

**Comment by datacharmer** [comment]
> I think the ux of remote download is broken by `--flavor`
It's actually working as expected, but it is an unpleasant surprise.

> It would be nice if the downloaded file could describe itself as mysql flavor so I can skip this argument?

Yep. I was thinking the same. This can be done easily.

**Pull request merged**
