### PR TITLE
Fix links in the table of contents in README.md

### PR DESCRIPTION
**Pull request by selurvedu**
Currently they are clickable, but have no effect.

### CODE REVIEW

**Comment by datacharmer** [comment]
Thanks for your contribution.
I could not find an official definition of how to define a table of contents in Markdown. 
Currently, the links work well for me on GitHub, and also work on several applications. In other applications, however, they don't work regardless of using lowercase or uppercase.
Do you know if there are recognised guidelines for using lowercase in `#links`?

**Comment by selurvedu** [comment]
@datacharmer
Indeed, the links work well on GitHub, but not on https://www.dbdeployer.com/, since the link targets don't exist. I simply changed them to match `id` attributes of the `<a>` tags that are present on a rendered HTML page. Apparently, GitHub has some magical JS code that makes the links work with any character case (lower or upper).

>  Do you know if there are recognised guidelines for using lowercase in #links?

I don't think there are any guidelines, it all depends on your markdown-to-HTML generator.

It converts each heading into a `<h1>`, `<h2>`, `<h3>`, `<h...>` tag with an `id` attribute which more or less matches the heading text. The exact ID generation algorithm depends on the converter you use. There is some info on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) about which characters are recommended in `id` attributes, but there are no strict constraints except the whitespace characters.

In general, I saw that `all-lowercase-words-separated-by-hyphens` is the most wide-spread format amongst the web.

**Comment by datacharmer** [comment]
Thanks for the research. I will generate a new README soon

**Comment by datacharmer** [comment]
The new README links seem to work in https://www.dbdeployer.com
Thanks again

**Pull request merged**
