### PR TITLE
Add pidfile support for TiDB

### PR DESCRIPTION
**Pull request by morgo**
I checked out how this is implemented in MySQL, and it is not a feature of `mysqld`, but rather `mysqld_safe`.  TiDB does not have a comparable to `mysqld_safe`, and since many modern oses use something like systemd for this instead, it does not make sense to implement one (it has been a source of many security vulnerabilities too).

So instead I modified the start script to generate a pid file, and modified the stop and status scripts to use it.  It seems to work fine (only tested on Linux, but I tried not to use any specific features).

The stop and status scripts check for the pid file, in addition to the start script checking for stale pid files.

### CODE REVIEW

**Comment by morgo** [comment]
> BTW, why do master downloads return different versions for MacOS and Linux? ([#62 (comment)](https://github.com/datacharmer/dbdeployer/issues/62#issuecomment-464472950)) I get 2.1.0 on MacOS and 3.0.0 on Linux.

I suspect that MacOS builds might not be regenerating daily.  Master should not be returning 3.0.0.  I will ask the build team to look into it, but in my mind, we should only be targeting 3.0+ since it has support for tcp+unix socket.  It will also now advertise socket/port/datadir correctly.

Thank you for the feedback, I will incorporate.

**Comment by morgo** [comment]
I've updated some temporary packages to:
https://s3.us-east-2.amazonaws.com/files.tocker.ca/tidb-master-darwin-amd64.tar.gz
https://s3.us-east-2.amazonaws.com/files.tocker.ca/tidb-master-linux-amd64.tar.gz

I've verified they work on Mac OS and Linux, but they were manually created.. so no guarantees.

I have incorporated the changes requested in your review.  In addition, the `use` and `status` commands now use the base templates.

**Comment by datacharmer** [comment]
Thanks for the update.
The good news is that `test_sb` passes. The bad ones is that the new `start` script is now mock-unfriendly.
Could you suggest a new template (similar to `mysqld_safe_mock_template`) that can emulate tidb-server so that the `start` script passes?

**Comment by morgo** [comment]
Sure, I'll take a look.

At quick glance it looks like the mock template writes a pid file (which in the case of TiDB the start script does), so conceptually it only needs to check that a `-config` argument was passed.  i.e.:

```
#!/bin/sh
# mock-tidb-server

options=$1

# check for -config

if echo $options | grep -F 'config' > /dev/null 2>&1
then
 echo "contains config"
 exit 0
else
 echo "no config!"
 exit 1
fi
```

Do I need to add a sleep in there so it is a "running server"?  I assume I don't need to patch `start` to accept a custom `tidb-server`, but rather a custom package is generated and unpacked?

**Comment by datacharmer** [comment]
Correct. We should not change `start` to pass a mock test.
However, a no-op mock-script fot tidb-drtbrt would not be enough, since `start` waits for a socket to appear.

The mock server is generated with a procedure similar to what we do in [set-mock.sh](https://github.com/datacharmer/dbdeployer/blob/master/test/mock/set-mock.sh).

The test that is failing is in [sandbox_test.go](https://github.com/datacharmer/dbdeployer/blob/1a285a3d39e7ef2e858ccf10f52cf0dfa047ada6/sandbox/sandbox_test.go#L221)

Run as
```
cd sandboxes
go test -v -run TestCreateSandbox/mocktidb .
```

**Pull request merged**
